# embed_assets.cmake — build-time bin2c for the overlay's embedded assets.
#
# Converts the repo-root overlay HTML and default background set into a
# generated C++ translation unit (byte-exact arrays + name/content-type table).
# The overlay HTML is served from memory (SC-007 byte-identity by
# construction); the bg images are the source for first-run extraction (D5).
#
# Usage (script mode):
#   cmake -DHTML_FILE=<path> -DBG_DIR=<path> -DOUT_CPP=<path> -P embed_assets.cmake

cmake_minimum_required(VERSION 3.24)

if(NOT HTML_FILE OR NOT BG_DIR OR NOT OUT_CPP)
    message(FATAL_ERROR "embed_assets.cmake requires -DHTML_FILE, -DBG_DIR, -DOUT_CPP")
endif()

if(NOT EXISTS "${HTML_FILE}")
    message(FATAL_ERROR "overlay HTML not found: ${HTML_FILE}")
endif()

# Hex-encode FILE and append a C array definition named SYMBOL to OUT_VAR.
# Chunked regex keeps CMake's regex engine fast on multi-MB inputs.
function(append_bin2c FILE SYMBOL OUT_VAR)
    file(READ "${FILE}" _hex HEX)
    string(LENGTH "${_hex}" _hexlen)
    math(EXPR _bytes "${_hexlen} / 2")
    set(_body "")
    set(_pos 0)
    set(_chunk 262144) # hex chars per chunk (128 KiB of payload)
    while(_pos LESS _hexlen)
        math(EXPR _remain "${_hexlen} - ${_pos}")
        if(_remain LESS _chunk)
            set(_take ${_remain})
        else()
            set(_take ${_chunk})
        endif()
        string(SUBSTRING "${_hex}" ${_pos} ${_take} _piece)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _piece "${_piece}")
        string(APPEND _body "${_piece}")
        math(EXPR _pos "${_pos} + ${_take}")
    endwhile()
    string(APPEND ${OUT_VAR}
        "static const unsigned char ${SYMBOL}[${_bytes}] = {\n${_body}\n};\n")
    set(${OUT_VAR} "${${OUT_VAR}}" PARENT_SCOPE)
    set(${OUT_VAR}_SIZE ${_bytes} PARENT_SCOPE)
endfunction()

function(content_type_for NAME OUT_VAR)
    string(TOLOWER "${NAME}" _lower)
    if(_lower MATCHES "\\.html$")
        set(${OUT_VAR} "text/html; charset=utf-8" PARENT_SCOPE)
    elseif(_lower MATCHES "\\.jpe?g$")
        set(${OUT_VAR} "image/jpeg" PARENT_SCOPE)
    elseif(_lower MATCHES "\\.png$")
        set(${OUT_VAR} "image/png" PARENT_SCOPE)
    elseif(_lower MATCHES "\\.gif$")
        set(${OUT_VAR} "image/gif" PARENT_SCOPE)
    elseif(_lower MATCHES "\\.webp$")
        set(${OUT_VAR} "image/webp" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "application/octet-stream" PARENT_SCOPE)
    endif()
endfunction()

set(_cpp "// GENERATED by component/tools/embed_assets.cmake — do not edit.\n")
string(APPEND _cpp "// Byte-exact embeds of nowplaying-overlay.html and bg/* (SC-007).\n")
string(APPEND _cpp "#include \"assets/embedded_assets.h\"\n#include <cstring>\n\n")
string(APPEND _cpp "namespace obs_overlay { namespace assets {\n\n")

set(_table "")
set(_count 0)

# Asset 0: the overlay HTML (served at "/").
append_bin2c("${HTML_FILE}" "k_asset_html" _cpp)
get_filename_component(_html_name "${HTML_FILE}" NAME)
string(APPEND _table "    { \"${_html_name}\", k_asset_html, sizeof(k_asset_html), \"text/html; charset=utf-8\" },\n")
math(EXPR _count "${_count} + 1")

# Default background set, sorted for reproducible builds.
if(EXISTS "${BG_DIR}")
    file(GLOB _bg_files LIST_DIRECTORIES false
        "${BG_DIR}/*.jpg" "${BG_DIR}/*.jpeg" "${BG_DIR}/*.png"
        "${BG_DIR}/*.gif" "${BG_DIR}/*.webp")
    list(SORT _bg_files)
    set(_idx 0)
    foreach(_bg IN LISTS _bg_files)
        get_filename_component(_bg_name "${_bg}" NAME)
        append_bin2c("${_bg}" "k_asset_bg_${_idx}" _cpp)
        content_type_for("${_bg_name}" _ctype)
        string(APPEND _table "    { \"bg/${_bg_name}\", k_asset_bg_${_idx}, sizeof(k_asset_bg_${_idx}), \"${_ctype}\" },\n")
        math(EXPR _idx "${_idx} + 1")
        math(EXPR _count "${_count} + 1")
    endforeach()
endif()

string(APPEND _cpp "static const EmbeddedAsset k_assets[${_count}] = {\n${_table}};\n\n")
string(APPEND _cpp "const EmbeddedAsset* assets_begin() { return k_assets; }\n")
string(APPEND _cpp "size_t assets_count() { return ${_count}; }\n\n")
string(APPEND _cpp "const EmbeddedAsset* overlay_html() { return &k_assets[0]; }\n\n")
string(APPEND _cpp "const EmbeddedAsset* find_asset(const char* name) {\n")
string(APPEND _cpp "    if (!name) return nullptr;\n")
string(APPEND _cpp "    for (size_t i = 0; i < ${_count}; ++i)\n")
string(APPEND _cpp "        if (std::strcmp(k_assets[i].name, name) == 0) return &k_assets[i];\n")
string(APPEND _cpp "    return nullptr;\n}\n\n")
string(APPEND _cpp "}} // namespace obs_overlay::assets\n")

file(WRITE "${OUT_CPP}" "${_cpp}")
message(STATUS "embed_assets: wrote ${_count} asset(s) to ${OUT_CPP}")
